chore(*): update libexec

diff --git a/libexec/build b/libexec/build
--- a/libexec/build
+++ b/libexec/build
@@ -1,4 +1,4 @@
-#!/bin/sh -eu
+#!/bin/sh -u
 
 cd "$(dirname "$0")"
 
@@ -18,6 +18,59 @@ cd '..'
 
 [ "$PWD" != "$(pwd -P)" ] && cd "$(pwd -P)"
 
+printf 'Cleaning up ... '
+
 "$PWD/libexec/clean" > '/dev/null' 2>&1
 
+echo 'done.'
+
+printf 'Copying source files ... '
+
 cp -R "$PWD/src" "$PWD/build" > '/dev/null' 2>&1
+
+__dotfiles_repo__build_cp_exit_status=$?
+
+if [ $__dotfiles_repo__build_cp_exit_status -eq 0 ]; then
+  echo 'succeeded.'
+
+  unset -v '__dotfiles_repo__build_cp_exit_status'
+else
+  echo 'failed.'
+
+  exit $__dotfiles_repo__build_cp_exit_status
+fi
+
+if [ -e "$PWD/vendor/git/github.com/ChristianGrete/dotfiles-cli/dist" ]; then
+  printf 'Making target directory for CLI ... '
+
+  mkdir "$PWD/build/opt/dotfiles.christiangrete.com" > '/dev/null' 2>&1
+
+  __dotfiles_repo__build_mkdir_exit_status=$?
+
+  if [ $__dotfiles_repo__build_mkdir_exit_status -eq 0 ]; then
+    echo 'succeeded.'
+
+    unset -v '__dotfiles_repo__build_mkdir_exit_status'
+  else
+    echo 'failed.'
+
+    exit $__dotfiles_repo__build_mkdir_exit_status
+  fi
+
+  printf 'Copying CLI artifact to target directory ... '
+
+  cp -R "$PWD/vendor/git/github.com/ChristianGrete/dotfiles-cli/dist" \
+    "$PWD/build/opt/dotfiles.christiangrete.com/cli" > '/dev/null' 2>&1
+
+  __dotfiles_repo__build_cp_exit_status=$?
+
+  if [ $__dotfiles_repo__build_cp_exit_status -eq 0 ]; then
+    echo 'succeeded.'
+
+    unset -v '__dotfiles_repo__build_cp_exit_status'
+  else
+    echo 'failed.'
+
+    exit $__dotfiles_repo__build_cp_exit_status
+  fi
+fi
diff --git a/libexec/clean b/libexec/clean
--- a/libexec/clean
+++ b/libexec/clean
@@ -1,4 +1,4 @@
-#!/bin/sh -eu
+#!/bin/sh -u
 
 cd "$(dirname "$0")"
 
@@ -18,6 +18,18 @@ cd '..'
 
 [ "$PWD" != "$(pwd -P)" ] && cd "$(pwd -P)"
 
-[ -e "$PWD/build" ] && rm -fr "$PWD/build"
+printf 'Removing build directory ... '
 
-exit 0
+rm -fr "$PWD/build" > '/dev/null' 2>&1
+
+__dotfiles_repo__clean_rm_exit_status=$?
+
+if [ $__dotfiles_repo__clean_rm_exit_status -eq 0 ]; then
+  echo 'succeeded.'
+
+  unset -v '__dotfiles_repo__clean_rm_exit_status'
+else
+  echo 'failed.'
+
+  exit $__dotfiles_repo__clean_rm_exit_status
+fi
